version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7.3
        environment:
          PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          name: install dependencies and run tests
          command: |
            make ci
      - store_artifacts:
          path: htmlcov
  run:
    docker:
      - image: circleci/python:3.7.3
        environment:
          PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          name: install dependencies and run tests
          command: |
            make ci
      - run:
          name: run
          command: make run
workflows:
  version: 2
  build-test:
    jobs:
      - test
  weekly:
    triggers:
      - schedule:
          cron: "0 9 * * 1"
          filters:
            branches:
              only: master
    jobs:
      - run
